# Generated by Django 4.0.4 on 2022-05-04 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignatedRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ride_request_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('A', 'Awaiting'), ('I', 'In progress'), ('F', 'Finished'), ('C', 'Cancelled')], default='A', max_length=1, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('start_location_latitude', models.FloatField(default=0)),
                ('start_location_longitude', models.FloatField(default=0)),
                ('end_location_latitude', models.FloatField(default=0)),
                ('end_location_longitude', models.FloatField(default=0)),
                ('adults_seats_number', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)], verbose_name='adults seats number')),
                ('children_seats_number', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='children seats number')),
                ('animal_seats_number', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='animal seats number')),
                ('trunk_capacity', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='trunk capacity')),
                ('air_conditioner_present', models.BooleanField(default=False, verbose_name='air conditioner present')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
