# Generated by Django 4.0.4 on 2022-05-04 11:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birth_date_user_first_name_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('ride_discount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=25, verbose_name='model')),
                ('type', models.CharField(choices=[('P', 'Passenger'), ('T', 'Truck'), ('M', 'Minivan')], max_length=25, verbose_name='type')),
                ('insurance_policy_number', models.CharField(max_length=25, verbose_name='insurance policy number')),
                ('adults_seats_number', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)], verbose_name='adults seats number')),
                ('children_seats_number', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='children seats number')),
                ('animal_seats_number', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='animal seats number')),
                ('trunk_capacity', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='trunk capacity')),
                ('air_conditioner_present', models.BooleanField(default=False, verbose_name='air conditioner present')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], default='U', max_length=1, verbose_name='gender'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('passport_number', models.CharField(max_length=25, verbose_name='passport number')),
                ('driver_license_number', models.CharField(max_length=25, verbose_name='driver license number')),
                ('taxi_license_number', models.CharField(max_length=25, verbose_name='taxi license number')),
                ('status', models.CharField(choices=[('N', 'Not verified'), ('I', 'Inactive'), ('A', 'Active'), ('B', 'Busy')], default='N', max_length=1, verbose_name='status')),
                ('vehicle', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vehicle')),
            ],
        ),
    ]
